version: '3.8'
    
services:
  app:
    image: go1/app:1.0
    build: ./app
    container_name: 'go1_app'
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ../app:/var/www/html
    depends_on:
      - db

  db:
    image: go1/mysql:1.0
    build: ./db
    container_name: 'go1_db'
    expose: 
      - "3306"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my
      - MYSQL_USER=my
      - MYSQL_PASSWORD=my
    volumes:
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d