version: '3.8'
    
services:
  app:
    image: node2/app:1.0
    build: ./app
    container_name: 'node2_app'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ../app:/var/www/html
    depends_on:
      - db

  db:
    image: mongo:4.4-bionic
    container_name: 'node2_db'
    expose: 
      - "27017"
    environment:
      - TZ=Asia/Tokyo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=mongo
    volumes:
      - ../db/database:/data/db
      - ../db/init:/docker-entrypoint-initdb.d

  web:
    image: nginx:1.19
    container_name: 'node2_web'
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html